import {
  Backspace,
  Divide,
  Equals,
  Minus,
  Percent,
  Plus,
  X,
} from "phosphor-react-native";

export const calculatorKeys = [
  { label: "C", icon: "C" },
  { label: "del", icon: <Backspace /> },
  { label: "%", icon: <Percent /> },
  { label: "/", icon: <Divide /> },
  { label: "7", icon: "7" },
  { label: "8", icon: "8" },
  { label: "9", icon: "9" },
  { label: "*", icon: <X /> },
  { label: "4", icon: "4" },
  { label: "5", icon: "5" },
  { label: "6", icon: "6" },
  { label: "-", icon: <Minus /> },
  { label: "1", icon: "1" },
  { label: "2", icon: "2" },
  { label: "3", icon: "3" },
  { label: "+", icon: <Plus /> },
  { label: "0", icon: "0" },
  { label: ".", icon: "." },
  { label: "", icon: "" },
  { label: "=", icon: <Equals /> },
];
